// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaORM;

namespace PracticaORM.Migrations
{
    [DbContext(typeof(ColegioContext))]
    [Migration("20200505234935_dos")]
    partial class dos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracticaORM.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("profesorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("profesorNavigatorprofesorID")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.HasIndex("profesorNavigatorprofesorID");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PracticaORM.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("cursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("cursoNavigatorCursoId")
                        .HasColumnType("int");

                    b.HasKey("EstudianteId");

                    b.HasIndex("cursoNavigatorCursoId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("PracticaORM.Profesor", b =>
                {
                    b.Property<int>("profesorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("sueldo")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("profesorID");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("PracticaORM.Curso", b =>
                {
                    b.HasOne("PracticaORM.Profesor", "profesorNavigator")
                        .WithMany("CursoNavigator")
                        .HasForeignKey("profesorNavigatorprofesorID");
                });

            modelBuilder.Entity("PracticaORM.Estudiante", b =>
                {
                    b.HasOne("PracticaORM.Curso", "cursoNavigator")
                        .WithMany("EstudiantesNavigator")
                        .HasForeignKey("cursoNavigatorCursoId");
                });
#pragma warning restore 612, 618
        }
    }
}
